apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-challange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-challange
  template:
    metadata:
      labels:
        app: go-api-challange
    spec:
      containers:
        - name: go-api-challange
          image: IMAGE_PATH
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "10Mi"
          env:
            - name: GO_ENV
              value: development
            - name: GCP_PROJECT_ID
              value: sandbox-toga4-gke
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
          nodeSelector:
            cloud.google.com/gke-spot: "true"
