apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
commonLabels:
  app: go-app-challange
images:
- name: IMAGE_PATH
  newName: gcr.io/sandbox-toga4-gke/go-app-challange
  newTag: latest
