name: Update manifest

on:
  repository_dispatch:
    types: [update-manifest]

env:
  GCLOUD_PROJECT: sandbox-toga4-gke

jobs:
  deploy:
    name: update-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update image path
        working-directory: kubernetes
        run: |
          kustomize edit set image IMAGE_PATH=gcr.io/$GCLOUD_PROJECT/${{ github.event.client_payload.service }}:${{ github.event.client_payload.sha }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "${{ github.event.client_payload.repo }}@${{ github.event.client_payload.sha }}"
          title: Deploy to GKE
          body: "Update image built from ${{ github.event.client_payload.repo }}@${{ github.event.client_payload.sha }}"
          branch: deploy/${{ github.event.client_payload.sha }}
          base: main
